# Generated by Django 4.2.7 on 2023-12-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_post_options_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Post content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fr',
            field=models.TextField(null=True, verbose_name='Post content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uk',
            field=models.TextField(null=True, verbose_name='Post content'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Post title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=250, null=True, verbose_name='Post title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Post title'),
        ),
    ]
